---
abstract: 'Moo eXtension for File::ConfigDir'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: '0.9'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-File-ConfigDir
no_index:
  directory:
    - t
    - inc
requires:
  File::ConfigDir: '0.011'
  Moo::Role: '1.003000'
  namespace::clean: '0'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooX-File-ConfigDir
  homepage: https://metacpan.org/release/MooX-File-ConfigDir
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-utils/MooX-File-ConfigDir
version: '0.004'
