---
abstract: 'Moo eXtension for File::ConfigDir'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-File-ConfigDir
no_index:
  directory:
    - t
    - inc
requires:
  File::ConfigDir: 0.011
  Moo::Role: 1.003000
  namespace::clean: 0
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
